baseurl = "https://fatmakahveci.com"
title = "Fatma Kahveci"
languageCode = "en-us"
paginate = "15" # Number of posts per page
theme = "mainroad"
disqusShortname = "www-fatmakahveci-com-1" # Enable comments by entering your Disqus shortname

[Author]
  name = "Fatma Kahveci"
  # bio = "https://github.com/fatmakahveci"
  # avatar = "img/avatar.png"

[Params]
  description = "Fatma Kahveci's Personal Blog" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = true # Show "Read more" button in list if true
  schema = true
  # toc = true # Enable Table of Contents
  googleAnalytics = "UA-49025750-1"
  # authorbox = true
  pager = true
  post_meta = ["author", "date", "categories"] # Order of post meta information
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdn.mathjax.org/mathjax/latest/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_SVG" # MathJax config
  highlightColor = "#4a5fc1" # Override highlight color
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files
  mainSections = ["coding note"]
  googleFontsLink = "https://fonts.googleapis.com/css2?family=Life+Savers:wght@700&display=swap"

[Params.style.vars]
  fontFamilyPrimary = "Montserrat, Arial"

[Params.widgets.social]
  twitter = "cheburashkaF"
  instagram = "fatmakhv"
  linkedin = "fatma-kahveci"
  github = "fatmakahveci"
  spotify = "fatmaths"
  # gitlab = "username"
  # bitbucket = "username"
  # email = "example@example.com"
  # facebook = "username"
  # telegram = "username"

[menu]

  [[menu.main]]
    identifier = "coding"
    name = "coding"
    url = "/coding note/"
    weight = -9

  [[menu.main]]
    identifier = "python"
    name = "python"
    url = "/python note/"
    weight = -8

  [[menu.main]]
    identifier = "django"
    name = "django"
    url = "/django note/"
    weight = -7

  [[menu.main]]
    identifier = "react"
    name = "react"
    url = "/react note/"
    weight = -6
  
  [[menu.main]]
    identifier = "go"
    name = "go"
    url = "/go note/"
    weight = -5

  [[menu.main]]
    identifier = "js"
    name = "js"
    url = "/javascript note/"
    weight = -4

  [[menu.main]]
    identifier = "bash"
    name = "bash"
    url = "/bash note/"
    weight = -3

  [[menu.main]]
    identifier = "aws"
    name = "aws"
    url = "/aws note/"
    weight = -2

  [[menu.main]]
    identifier = "travel"
    name = "Travel"
    url = "/travel note/"
    weight = -1

[Params.logo]
  subtitle = "" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = [ "recent", "social","taglist" ] # "categories"

[Params.widgets]
  recent_num = 10 # Set the number of articles in the "Recent articles" widget
  # tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)
